// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DepartmentCityPickerController from "./department_city_picker_controller"
application.register("department-city-picker", DepartmentCityPickerController)

import FlashActionsController from "./flash_actions_controller"
application.register("flash-actions", FlashActionsController)

import MapController from "./map_controller"
application.register("maps", MapController)
