// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DepartmentCityPickerController from "./department_city_picker_controller"
application.register("department-city-picker", DepartmentCityPickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MuseumRegistrationRequestController from "./museum_registration_request_controller"
application.register("museum-registration-request", MuseumRegistrationRequestController)
